name             'autossh-init'
maintainer       'Nico Kadel-Garcia'
maintainer_email 'nkadel@skyhookwireless.com'
license          'All rights reserved'
description      'Installs/Configures autossh init scripts'
version          '0.1.2'

supports 'redhat'
supports 'centos'
supports 'fedora'
supports 'scientific'
supports 'amazon'
supports 'oracle'
